bodies:
- BODY ExoHip
- BODY ExoLeftThigh
- BODY ExoLeftShank
- BODY ExoLeftFoot
- BODY ExoRightThigh
- BODY ExoRightShank
- BODY ExoRightFoot
joints:
- JOINT ExoLeftKnee
- JOINT ExoLeftAnkle
- JOINT ExoRightKnee
- JOINT ExoRightAnkle
- JOINT ExoRightHip
high resolution path: ./high_res/
low resolution path: ./low_res/
ignore inter-collision: false
namespace: /ambf/env/

BODY ExoHip:
  name: ExoHip
  mesh: ExoHip.STL
  mass: 45.32
  inertia:
    ix: 3.6292
    iy: 4.1578
    iz: 1.1847
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: -0.0001
      y: -0.0
      z: 0.2001
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: 0.0001
      y: -0.0785
      z: 0.2803
    orientation:
      r: 0
      p: 0
      y: 0
  passive: false
  publish children names: false
  publish joint names: true
  publish joint positions: true
  friction:
    rolling: 0.01
    static: 0.5
  restitution: 0.0
  damping:
    angular: 0.5
    linear: 0.5
  collision groups:
  - 8
  collision shape: BOX
  collision geometry:
    x: 0.4763
    y: 0.2835
    z: 0.6854
  collision offset:
    position:
      x: 0.0001
      y: -0.0232
      z: 0.1836
    orientation:
      r: 0.0
      p: 0.0
      y: 0.0
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 0.0
      g: 1.0
      r: 0.0
    specular:
      b: 0.5
      g: 0.5
      r: 0.0
    transparency: 1.0
BODY ExoLeftThigh:
  name: ExoLeftThigh
  mesh: ExoLeftThigh.STL
  mass: 13.934
  inertia:
    ix: 0.5435
    iy: 0.6347
    iz: 0.1249
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: 0.24
      y: -0.1249
      z: -0.0766
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: -0.0833
      y: -0.0198
      z: -0.0678
    orientation:
      r: 0
      p: 0
      y: 0
  passive: true
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.01
    static: 0.5
  restitution: 0.0
  damping:
    angular: 0.1
    linear: 0.5
  collision groups:
  - 5
  collision shape: CAPSULE
  collision geometry:
    axis: Z
    height: 0.5553
    radius: 0.0558
  collision offset:
    position:
      x: 0.0223
      y: 0.0006
      z: -0.0857
    orientation:
      r: 0.0
      p: 0.0
      y: 0.0
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 1.0
      g: 0.0
      r: 0.0
    specular:
      b: 0.0
      g: 0.0
      r: 0.0
    transparency: 1.0
BODY ExoLeftShank:
  name: ExoLeftShank
  mesh: ExoLeftShank.STL
  mass: 5.104
  inertia:
    ix: 0.1359
    iy: 0.1834
    iz: 0.0559
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: 0.264
      y: -0.1224
      z: -0.6356
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: -0.0968
      y: 0.0078
      z: 0.0547
    orientation:
      r: 0
      p: 0
      y: 0
  passive: true
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.01
    static: 0.5
  restitution: 0.0
  damping:
    angular: 0.1
    linear: 0.5
  collision groups:
  - 6
  collision shape: CAPSULE
  collision geometry:
    axis: Z
    height: 0.4529
    radius: 0.0534
  collision offset:
    position:
      x: -0.0238
      y: -0.0001
      z: 0.058
    orientation:
      r: 0.0
      p: 0.0
      y: 0.0
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 1.0
      g: 0.0
      r: 0.0
    specular:
      b: 0.0
      g: 0.0
      r: 0.0
    transparency: 1.0
BODY ExoLeftFoot:
  name: ExoLeftFoot
  mesh: ExoLeftFoot.STL
  mass: 1.898
  inertia:
    ix: 0.0339
    iy: 0.0269
    iz: 0.0242
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: 0.2425
      y: -0.125
      z: -0.8331
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: -0.0733
      y: -0.0583
      z: 0.0458
    orientation:
      r: 0
      p: 0
      y: 0
  passive: true
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.1
    static: 0.5
  restitution: 0.1
  damping:
    angular: 0.1
    linear: 0.5
  collision groups:
  - 7
  collision shape: BOX
  collision geometry:
    x: 0.2283
    y: 0.3141
    z: 0.1809
  collision offset:
    position:
      x: -0.0733
      y: -0.0583
      z: 0.0518
    orientation:
      r: 0.0
      p: 0.0
      y: 0.0
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 1.0
      g: 0.0
      r: 0.0
    specular:
      b: 0.0
      g: 0.0
      r: 0.0
    transparency: 1.0
BODY ExoRightThigh:
  name: ExoRightThigh
  mesh: ExoRightThigh.STL
  mass: 13.934
  inertia:
    ix: 0.5767
    iy: 0.5836
    iz: 0.0297
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: -0.24
      y: -0.1249
      z: -0.0766
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: 0.079
      y: -0.0198
      z: -0.0678
    orientation:
      r: 0
      p: 0
      y: 0
  passive: true
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.5
    static: 0.5
  restitution: 0.0
  damping:
    angular: 0.1
    linear: 0.1
  collision groups:
  - 15
  collision shape: CAPSULE
  collision geometry:
    axis: Z
    height: 0.5553
    radius: 0.0558
  collision offset:
    position:
      x: -0.0223
      y: 0.0009
      z: -0.0859
    orientation:
      r: 0.0
      p: 0.0
      y: 0.0
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 0.0
      g: 0.0
      r: 1.0
    specular:
      b: 0.0
      g: 0.0
      r: 0.5
    transparency: 1.0
BODY ExoRightShank:
  name: ExoRightShank
  mesh: ExoRightShank.STL
  mass: 5.104
  inertia:
    ix: 0.1359
    iy: 0.1812
    iz: 0.0536
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: -0.268
      y: -0.1224
      z: -0.6356
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: 0.0945
      y: 0.0078
      z: 0.0547
    orientation:
      r: 0
      p: 0
      y: 0
  passive: true
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.01
    static: 0.5
  restitution: 0.0
  damping:
    angular: 0.5
    linear: 0.5
  collision groups:
  - 16
  collision shape: CAPSULE
  collision geometry:
    axis: Z
    height: 0.4529
    radius: 0.0534
  collision offset:
    position:
      x: 0.0237
      y: -0.0001
      z: 0.058
    orientation:
      r: 0.0
      p: 0.0
      y: 0.0
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 0.0
      g: 0.0
      r: 1.0
    specular:
      b: 0.0
      g: 0.0
      r: 0.5
    transparency: 1.0
BODY ExoRightFoot:
  name: ExoRightFoot
  mesh: ExoRightFoot.STL
  mass: 1.898
  inertia:
    ix: 0.0339
    iy: 0.0269
    iz: 0.0242
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: -0.2425
      y: -0.125
      z: -0.8331
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: 0.0734
      y: -0.0582
      z: 0.0457
    orientation:
      r: 0
      p: 0
      y: 0
  passive: true
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.1
    static: 0.5
  restitution: 0.1
  damping:
    angular: 0.1
    linear: 0.5
  collision groups:
  - 17
  collision shape: BOX
  collision geometry:
    x: 0.2283
    y: 0.3141
    z: 0.1809
  collision offset:
    position:
      x: 0.0734
      y: -0.0582
      z: 0.0518
    orientation:
      r: 0.0
      p: 0.0
      y: 0.0
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 0.0
      g: 0.0
      r: 1.0
    specular:
      b: 0.0
      g: 0.0
      r: 0.5
    transparency: 1.0
  controller:
    linear:
      P: 500.0
      I: 5.0
      D: 5.0
    angular:
      P: 50.0
      I: 0.5
      D: 0.5

JOINT ExoLeftKnee:
  name: ExoLeftKnee
  parent: BODY ExoLeftThigh
  child: BODY ExoLeftShank
  parent axis:
    x: 1.0
    y: 0.0
    z: 0.0
  parent pivot:
    x: -0.003
    y: 0.0012
    z: -0.3038
  child axis:
    x: 1.0
    y: 0.0
    z: 0.0
  child pivot:
    x: -0.027
    y: -0.0014
    z: 0.2552
  joint limits:
    high: 1.92
    low: 0.0
  enable feedback: true
  passive: false
  body rotation:
    xx: 1.0
    xy: 0.0
    xz: 0.0
    yx: 0.0
    yy: 1.0
    yz: 0.0
    zx: 0.0
    zy: 0.0
    zz: 1.0
  detached: true
  type: revolute
  max motor impulse: 0.05000000074505806
  damping: 0.5
JOINT ExoLeftAnkle:
  name: ExoLeftAnkle
  parent: BODY ExoLeftShank
  child: BODY ExoLeftFoot
  parent axis:
    x: 1.0
    y: 0.0
    z: 0.0
  parent pivot:
    x: 0.0002
    y: 0.0005
    z: -0.1401
  child axis:
    x: 1.0
    y: 0.0
    z: 0.0
  child pivot:
    x: 0.0217
    y: 0.0031
    z: 0.0574
  joint limits:
    high: 0.5236
    low: -0.7854
  enable feedback: true
  passive: false
  controller:
    P: 2135.3999
    I: 5.0
    D: 4.271
  body rotation:
    xx: 1.0
    xy: 0.0
    xz: 0.0
    yx: 0.0
    yy: 1.0
    yz: 0.0
    zx: 0.0
    zy: 0.0
    zz: 1.0
  detached: true
  type: revolute
  max motor impulse: 0.05000000074505806
  damping: 0.5
JOINT ExoRightKnee:
  name: ExoRightKnee
  parent: BODY ExoRightThigh
  child: BODY ExoRightShank
  parent axis:
    x: 1.0
    y: 0.0
    z: 0.0
  parent pivot:
    x: -0.001
    y: 0.0012
    z: -0.3038
  child axis:
    x: 1.0
    y: 0.0
    z: 0.0
  child pivot:
    x: 0.027
    y: -0.0014
    z: 0.2552
  joint limits:
    high: 1.92
    low: 0.0
  enable feedback: true
  passive: false
  controller:
    P: 3394.2
    I: 5.0
    D: 6.788
  body rotation:
    xx: 1.0
    xy: 0.0
    xz: 0.0
    yx: 0.0
    yy: 1.0
    yz: 0.0
    zx: 0.0
    zy: 0.0
    zz: 1.0
  detached: true
  type: revolute
  max motor impulse: 0.05000000074505806
  damping: 0.5
JOINT ExoRightAnkle:
  name: ExoRightAnkle
  parent: BODY ExoRightShank
  child: BODY ExoRightFoot
  parent axis:
    x: 1.0
    y: 0.0
    z: 0.0
  parent pivot:
    x: 0.0038
    y: 0.0005
    z: -0.1401
  child axis:
    x: 1.0
    y: 0.0
    z: 0.0
  child pivot:
    x: -0.0217
    y: 0.0031
    z: 0.0574
  joint limits:
    high: 0.5236
    low: -0.7854
  enable feedback: true
  passive: false
  controller:
    P: 2135.3999
    I: 5.0
    D: 4.271
  body rotation:
    xx: 1.0
    xy: 0.0
    xz: 0.0
    yx: 0.0
    yy: 1.0
    yz: 0.0
    zx: 0.0
    zy: 0.0
    zz: 1.0
  detached: true
  type: revolute
  max motor impulse: 0.05000000074505806
  damping: 0.5
JOINT ExoRightHip:
  name: ExoRightHip
  parent: BODY ExoHip
  child: BODY ExoRightThigh
  parent axis:
    x: 1.0
    y: 0.0
    z: 0.0
  parent pivot:
    x: -0.2369
    y: -0.124
    z: -0.1441
  child axis:
    x: 1.0
    y: 0.0
    z: 0.0
  child pivot:
    x: 0.003
    y: 0.0009
    z: 0.1326
  joint limits:
    high: 0.524
    low: -1.92
  enable feedback: true
  passive: false
  body rotation:
    xx: 1.0
    xy: 0.0
    xz: 0.0
    yx: 0.0
    yy: 1.0
    yz: 0.0
    zx: 0.0
    zy: 0.0
    zz: 1.0
  detached: true
  type: revolute
  max motor impulse: 0.05000000074505806
  damping: 0.5
